import React, { useState, useCallback, useEffect } from 'react';
import { useFocusEffect } from '@react-navigation/native';
import { useSelector } from 'react-redux';
import { RootState } from '../redux/store'
import { View, StyleSheet, FlatList, TouchableOpacity, Text, DeviceEventEmitter, ActivityIndicator, Alert } from 'react-native';
import { FileText, Download, Eye } from 'lucide-react-native';
import api from '../services/api';
import { mockPayslips } from '../mockData/mockData';
import AddPayslipModal from '../components/AddPayslipModal';

export default function MyPayslipScreen() {
  const { user } = useSelector((state: RootState) => state.auth);
  const isAdminOrHR = user?.role?.toLowerCase() === 'admin' || user?.role?.toLowerCase() === 'hr';
  const [localPayslips, setLocalPayslips] = useState<any[]>([]);
  const [isModalVisible, setModalVisible] = useState(false);
  const [loading, setLoading] = useState(true);

  const fetchPayslips = async () => {
    try {
      setLoading(true);
      const res = await api.get('/payroll/my');
      // Adjusting map if the backend returns specific fields
      const formatted = (res.data.data?.payroll || []).map((p: any) => ({
        id: p._id,
        period: p.period || `${p.month}`,
        amount: `$${p.netSalary || p.netPay}`,
        status: p.status,
      }));
      setLocalPayslips(formatted);
    } catch (error: any) {
      console.log('Error fetching payslips:', error);
    } finally {
      setLoading(false);
    }
  };

  useFocusEffect(
    useCallback(() => {
      fetchPayslips();
      const subscription = DeviceEventEmitter.addListener('onAddAction', () => setModalVisible(true));
      return () => subscription.remove();
    }, [])
  );

  const handleAddPayslip = async (period: string, amount: string, status: string) => {
    // Usually payslips are added via a generate payroll endpoint.
    // For demo/modal purposes if we have a mock modal, we just show alert:
    Alert.alert('Info', 'Payslips should be generated by HR via Admin panel.');
  };

  return (
    <View style={styles.container}>
      {loading ? (
        <ActivityIndicator size="large" color="#3B82F6" style={{ marginTop: 20 }} />
      ) : (
        <FlatList
        data={localPayslips}
        keyExtractor={(item) => item.id}
        renderItem={({ item }) => {
          const isPaid = item.status?.toLowerCase() === 'paid';
          return (
            <View style={styles.modernCard}>
              <View style={styles.cardHeader}>
                <View style={{ flexDirection: 'row', alignItems: 'center' }}>
                  <View style={styles.iconWrapper}>
                    <FileText color="#10B981" size={24} />
                  </View>
                  <View>
                    <Text style={styles.title}>{item.period}</Text>
                    <Text style={styles.subtitle}>Salary Slip</Text>
                  </View>
                </View>
                <View style={[styles.statusBadge, isPaid ? styles.badgeGreen : styles.badgeOrange]}>
                  <Text style={[styles.statusText, isPaid ? styles.textGreen : styles.textOrange]}>{item.status}</Text>
                </View>
              </View>
              
              <View style={styles.cardBody}>
                <Text style={styles.amountLabel}>Net Pay</Text>
                <Text style={styles.amountValue}>{item.amount}</Text>
              </View>

              <View style={styles.cardFooter}>
                <TouchableOpacity style={styles.actionBtn}>
                  <Eye color="#64748B" size={18} />
                  <Text style={styles.actionBtnText}>View</Text>
                </TouchableOpacity>
                <TouchableOpacity style={styles.actionBtn}>
                  <Download color="#64748B" size={18} />
                  <Text style={styles.actionBtnText}>Download</Text>
                </TouchableOpacity>
              </View>
            </View>
          );
        }}
        ListEmptyComponent={
          <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center', marginTop: 60 }}>
            <Text style={{ color: '#64748B', fontSize: 16, fontWeight: '500' }}>No payslips available</Text>
          </View>
        }
      />
      )}
      <AddPayslipModal 
        visible={isModalVisible} 
        onClose={() => setModalVisible(false)} 
        onSave={handleAddPayslip} 
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8FAFC', padding: 16 },
  modernCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  iconWrapper: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#ECFDF5',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  title: {
    color: '#0F172A',
    fontSize: 16,
    fontWeight: '700',
  },
  subtitle: {
    color: '#64748B',
    fontSize: 12,
    fontWeight: '500',
  },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  badgeGreen: { backgroundColor: '#ECFDF5' },
  badgeOrange: { backgroundColor: '#FFFBEB' },
  textGreen: { color: '#059669', fontSize: 12, fontWeight: '700', textTransform: 'uppercase' },
  textOrange: { color: '#D97706', fontSize: 12, fontWeight: '700', textTransform: 'uppercase' },
  cardBody: {
    padding: 16,
    alignItems: 'flex-start',
  },
  amountLabel: {
    color: '#64748B',
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 4,
  },
  amountValue: {
    color: '#0F172A',
    fontSize: 28,
    fontWeight: '800',
  },
  cardFooter: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  actionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    gap: 8,
  },
  actionBtnText: {
    color: '#64748B',
    fontSize: 14,
    fontWeight: '600',
  },
});
